apiVersion: apps/v1
kind: Deployment
metadata:
  name: authmodule
spec:
  selector:
    matchLabels:
      app: authmodule
  replicas: 1
  template:
    metadata:
      labels:
        app: authmodule
    spec:
      containers:
      - name: authmodule
        image: DeekshaSh/authmodule
 
---
apiVersion: v1
kind: Service
metadata:
  name: authmodule
spec:
  type: NodePort
  selector:
    app: authmodule
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 31000
